Move docker-sync and related tools to the end of auto-install-3rd-party-tools

diff --git a/helpers/modofu-real b/helpers/modofu-real
--- a/helpers/modofu-real
+++ b/helpers/modofu-real
@@ -187,6 +187,43 @@ deal_with_3rd_party_tools()
       fi
     fi
 
+    if ! [ -x "$(which socat)" ]; then
+      echo "W: Command socat not found" 1>&2
+      if [ "$mode" = "auto_install" ]; then
+        echo "I: Trying to install it. You might need to provide your password..." 1>&2
+        brew install socat
+        echo "I: Installed." 1>&2
+      else
+        echo "E: Please install it manually or use '# $MODOFU_SCRIPT_NAME auto-install-3rd-party-tools" 1>&2
+        exit 1
+      fi
+    fi
+
+    if ! [ -x "$(which screen)" ] || \
+         [ $(screen -v | grep -c -i GNU) -le 0 ]; then
+      echo "W: Command screen not found or not the GNU variant" 1>&2
+      if [ "$mode" = "auto_install" ]; then
+        echo "I: Trying to install it. You might need to provide your password..." 1>&2
+        brew install screen
+        echo "I: Installed." 1>&2
+      else
+        echo "E: Please install the GNU variant of screen manually or use '# $MODOFU_SCRIPT_NAME auto-install-3rd-party-tools" 1>&2
+        exit 1
+      fi
+    fi
+
+    if ! [ -x "$(which pstree)" ]; then
+      echo "W: Command pstree not found" 1>&2
+      if [ "$mode" = "auto_install" ]; then
+        echo "I: Trying to install it. You might need to provide your password..." 1>&2
+        brew install pstree
+        echo "I: Installed." 1>&2
+      else
+        echo "E: Please install it manually or use '# $MODOFU_SCRIPT_NAME auto-install-3rd-party-tools" 1>&2
+        exit 1
+      fi
+    fi
+
     if ! [ -x "$(which unison)" ]; then
       echo "W: Command unison not found" 1>&2
       if [ "$mode" = "auto_install" ]; then
@@ -225,43 +262,6 @@ deal_with_3rd_party_tools()
       docker-sync -v 1>/dev/null 2>&1 || docker_sync_working=0
       if [ $docker_sync_working -ne 1 ]; then
         echo "E: Your docker-sync installation is broken. Please ensure you can successfully run at least '# docker-sync -v'" 1>&2
-        exit 1
-      fi
-    fi
-
-    if ! [ -x "$(which socat)" ]; then
-      echo "W: Command socat not found" 1>&2
-      if [ "$mode" = "auto_install" ]; then
-        echo "I: Trying to install it. You might need to provide your password..." 1>&2
-        brew install socat
-        echo "I: Installed." 1>&2
-      else
-        echo "E: Please install it manually or use '# $MODOFU_SCRIPT_NAME auto-install-3rd-party-tools" 1>&2
-        exit 1
-      fi
-    fi
-
-    if ! [ -x "$(which screen)" ] || \
-         [ $(screen -v | grep -c -i GNU) -le 0 ]; then
-      echo "W: Command screen not found or not the GNU variant" 1>&2
-      if [ "$mode" = "auto_install" ]; then
-        echo "I: Trying to install it. You might need to provide your password..." 1>&2
-        brew install screen
-        echo "I: Installed." 1>&2
-      else
-        echo "E: Please install the GNU variant of screen manually or use '# $MODOFU_SCRIPT_NAME auto-install-3rd-party-tools" 1>&2
-        exit 1
-      fi
-    fi
-
-    if ! [ -x "$(which pstree)" ]; then
-      echo "W: Command pstree not found" 1>&2
-      if [ "$mode" = "auto_install" ]; then
-        echo "I: Trying to install it. You might need to provide your password..." 1>&2
-        brew install pstree
-        echo "I: Installed." 1>&2
-      else
-        echo "E: Please install it manually or use '# $MODOFU_SCRIPT_NAME auto-install-3rd-party-tools" 1>&2
         exit 1
       fi
     fi
